---
title: Hodometer architecture
---

flowchart TD
  H["Hodometer\n\nMetrics publisher"]
  K["Kubernetes API"]
  S["Core v2 Scheduler"]
  R1["Receiver"]
  R2["Extra Receiver"]
  R3["Extra Receiver"]
