---
title: Spartakus architecture
---

flowchart TD
  S["Volunteer

    Spartakus metrics publisher"
  ]

  C["Collector

    Spartakus metrics receiver"
  ]

  K["Kubernetes API"]

  C --> |metrics pushed from| S
  S --> |queries| K
