---
title: Spartakus architecture
---

flowchart TD
  S["Volunteer\n\nSpartakus metrics publisher"]
  C["Collector\n\nSpartakus metrics receiver"]
  K["Kubernetes API"]

  subgraph Kubernetes cluster
    S --> |queries| K
  end
  S ---> |pushes metrics to| C

  classDef focusSystem      fill:#1168bd,stroke:#0b4884,color:#ffffff
  classDef supportingSystem fill:#666,stroke:#0b4884,color:#ffffff
  classDef consumingSystem  fill:#08427b,stroke:#052e56,color:#ffffff

  class S focusSystem
  class C consumingSystem
  class K supportingSystem
