---
title: Operator context diagram
---

flowchart TD
  U["User"]
  K["Kubernetes API"]
  O["Operator"]
  C["Seldon Core v2"]

  U --> |"submits resources"| KC
  subgraph KC["Kubernetes cluster"]
    K ---> |"sends status updates"| O
    O ---> |"sends resources"| C
    O ---> |"sends resources"| K
    C ---> |"sends status updates"| O
  end

  classDef focusSystem      fill:#1168bd,stroke:#0b4884,color:#ffffff
  classDef supportingSystem fill:#666,stroke:#0b4884,color:#ffffff
  classDef consumingSystem  fill:#08427b,stroke:#052e56,color:#ffffff
  classDef systemBoundary   fill:#eee,stroke:#ccc,stroke-width:2px,stroke-dasharray: 5 5

  class O focusSystem
  class K,C supportingSystem
  class U consumingSystem
  class KC systemBoundary
