title: Software for the Sedentary
description: MLOps, musings, and more

github_username: agrski
author:
  name: A G Rakowski
  url: https://github.com/agrski
repository: agrski/agrski.github.io

theme: jekyll-theme-midnight
locale: en_GB
markdown: kramdown
paginate: 1
show_downloads: false
